### PR TITLE
Fix GitHub actions

### PR DESCRIPTION
**Pull request by kwongtn**
Attempting to fix github actions.

### CODE REVIEW

**Review by korniltsev — APPROVED** [review]

**Comment by korniltsev** [comment]
Idk, how to grant permission to run actions automatically and if it is permitted by grafana org.
I guess I have to hit "approve" every time. Ping me if I miss something.

Another thing you can do is to create a fork and run  workflows in your fork ( it probably will not help with macOS arm64 runners though)

**Comment by kwongtn** [comment]
@korniltsev can you run the actions? I think everything is done for ruby side -- for python there are some issues with the build wheels that I'm working on

**Comment by korniltsev** [comment]
we cannot use `stable` toolchain.  We need a fixed version. Moreover we should use the same toolchain version everywhere i.e. dockerfiles https://github.com/grafana/pyroscope-rs/blob/d1d29940fdbf0801042c90bae55f1c34a52265fb/docker/Dockerfile.manylinux2014_aarch64#L6

**Review by korniltsev — CHANGES_REQUESTED** [review]
- please fix a specific toolchain version, not `stable`
- lets try using `macos-14` runners? The "11.0" we used to use is now offline and unavailable.

**Comment by korniltsev** [comment]
Thank you a lot! :tada:

**Comment by kwongtn** [comment]
@korniltsev I think its ready 👀

**Review by korniltsev — CHANGES_REQUESTED** [review]
Toolchain is still stable in workflows. Please Either fix it ~or try to remove toolchain altogether if possible~

**Comment by korniltsev** [comment]
Also am I understanding correctly that we are switching from arm native runner to running arm on qemu? If so, we better bring back native execution for speed, we dont need slow builds.

**Comment by korniltsev** [comment]
Great job!

**Comment by kwongtn** [comment]
> Also am I understanding correctly that we are switching from arm native runner to running arm on qemu? If so, we better bring back native execution for speed, we dont need slow builds.

Got it. Reverted at a29824aacd09d4a640b935ead622bdaa78b37af3 
Thought the runner was not valid

> Toolchain is still stable in workflows.

Fixed 😁
1f3f80be5058345be9f06f64ecfb6479efc9aec1

**Review by korniltsev — APPROVED** [review]
lets gooo!

I recokn there maybe more issues with release/publish pipelines since we did not trigger them in this PR. I will try to release python today.

**Pull request merged**
